on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - infra/**
  push:
    branches:
      - master
    paths:
      - infra/**

concurrency:
  group: environment-${{ github.ref }}-terragrunt-infra

name: Terragrunt Deployment

permissions:
  id-token: write
  contents: read

env:
  TOOLS_BASE: .github/scripts
  GITHUB_USER_TOKEN: ${{ secrets.WORKFLOW_PAT }}
  GITHUB_USER_EMAIL: amirasyraf@outlook.com
  GITHUB_USER_NAME: amirasyraf
  AWS_REGION: ap-southeast-2
  AWS_ARN_ROLE: ${{ secrets.AWS_ROLE_ARN }}
  TERRAGRUNT_ROOT: infra

jobs:
  terragrunt-plan:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure AWS CLI - Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ARN_ROLE }}
          role-session-name: terragrunt
          aws-region: ${{ env.AWS_REGION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: /home/linuxbrew/.linuxbrew/
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install asdf
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install asdf

      - name: Install tools
        working-directory: ${{ env.TOOLS_BASE }}
        run: |
          bash install-tools-asdf.sh

      - name: Configure Git credentials
        run: |
          git config --global url."https://${{ env.GITHUB_USER_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
          git config --global user.email ${{ env.GITHUB_USER_EMAIL }}
          git config --global user.name ${{ env.GITHUB_USER_NAME }}

      - name: Perform pre-commit checks
        run: |
          . /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh
          pre-commit --version
          pre-commit install
          pre-commit run --all-files

      - name: Execute terragrunt
        working-directory: ${{ env.TERRAGRUNT_ROOT }}
        run: |
          . /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh
          terragrunt --version
          terragrunt run-all plan --terragrunt-non-interactive -out=output.tfplan

      - name: Plan summary
        working-directory: ${{ env.TERRAGRUNT_ROOT }}
        run: |
          . /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh
          find . -type f -name "output.tfplan" | xargs -I {} sh -c 'path=$(dirname "{}"); \
          echo "\n*** Processing ${path%%/.terragrunt-cache/*}:"; \
          cd "$path" && terraform show "output.tfplan"'

      - name: Plan summary -- tf-summarize -tree
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ${{ env.TERRAGRUNT_ROOT }}
        run: |
          . /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh
          find . -type f -name "output.tfplan" | xargs -I {} sh -c 'path=$(dirname "{}"); \
          echo "\n*** Processing ${path%%/.terragrunt-cache/*}:"; \
          cd "$path" && terraform show -json "output.tfplan" | tf-summarize -tree'

  terragrunt-apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure AWS CLI - Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ARN_ROLE }}
          role-session-name: terragrunt
          aws-region: ${{ env.AWS_REGION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: /home/linuxbrew/.linuxbrew/
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install asdf
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install asdf

      - name: Install tools
        working-directory: ${{ env.TOOLS_BASE }}
        run: |
          bash install-tools-asdf.sh

      - name: Configure Git credentials
        run: |
          git config --global url."https://${{ env.GITHUB_USER_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
          git config --global user.email ${{ env.GITHUB_USER_EMAIL }}
          git config --global user.name ${{ env.GITHUB_USER_NAME }}

      - name: Execute terragrunt
        working-directory: ${{ env.TERRAGRUNT_ROOT }}
        run: |
          . /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh
          terragrunt run-all apply --terragrunt-non-interactive
